import type { RepoFacts } from './types.js';

const START = '<!-- agentcontextkit:start -->';
const END = '<!-- agentcontextkit:end -->';
const LEGACY_START = '<!-- repobrief:start -->';
const LEGACY_END = '<!-- repobrief:end -->';

export function withManagedBlock(existing: string | undefined, body: string): string {
  const block = `${START}\n${body.trim()}\n${END}\n`;
  if (!existing || existing.trim().length === 0) return block;
  for (const [start, end] of [
    [START, END],
    [LEGACY_START, LEGACY_END]
  ]) {
    const pattern = new RegExp(`${escapeRegex(start)}[\\s\\S]*?${escapeRegex(end)}\\n?`, 'm');
    if (pattern.test(existing)) return existing.replace(pattern, block);
  }
  const separator = existing.endsWith('\n') ? '\n' : '\n\n';
  return `${existing}${separator}${block}`;
}

export function renderAgents(facts: RepoFacts): string {
  return renderCommon(facts, 'AgentContextKit Context');
}

export function renderClaude(facts: RepoFacts): string {
  return renderCommon(facts, 'AgentContextKit Context for Claude Code');
}

export function renderCursor(facts: RepoFacts): string {
  return `---\ndescription: AgentContextKit generated project context\nalwaysApply: true\n---\n\n${renderCommon(facts, 'AgentContextKit Context for Cursor')}`;
}

export function renderCopilot(facts: RepoFacts): string {
  return `${renderCommon(facts, 'AgentContextKit Context for GitHub Copilot')}\n\nUse the commands below before proposing large changes.`;
}

export function renderRepoMap(facts: RepoFacts): string {
  return `# Repo map\n\nGenerated by AgentContextKit for \`${facts.rootName}\`.\n\n## Stack\n\n- Package managers: ${listOrNone(facts.packageManagers)}\n- Languages: ${listOrNone(facts.languages)}\n- Framework hints: ${listOrNone(facts.frameworks)}\n\n## Important folders\n\n${bullets(facts.importantFolders)}\n\n## Commands\n\n${commandBullets(facts)}\n\n## Existing agent docs at scan time\n\n${bullets(facts.existingAgentDocs)}\n`;
}

function renderCommon(facts: RepoFacts, title: string): string {
  return `# ${title}\n\nAgentContextKit generated this block from repository facts. Preserve hand-written notes outside the managed markers.\n\n## Project\n\n- Repository: \`${facts.rootName}\`\n- Package managers: ${listOrNone(facts.packageManagers)}\n- Languages: ${listOrNone(facts.languages)}\n- Framework hints: ${listOrNone(facts.frameworks)}\n\n## Working commands\n\n${commandBullets(facts)}\n\n## Important folders\n\n${bullets(facts.importantFolders)}\n\n## Agent-doc safety\n\nAgentContextKit owns only content between the managed start and end marker comments. Keep project-specific human guidance outside those markers.\n\n## Source facts\n\nSee \`.agent-context/facts.json\` and \`.agent-context/repo-map.md\` for the raw scan output and concise repo map.\n`;
}

function commandBullets(facts: RepoFacts): string {
  const entries = Object.entries(facts.commands);
  if (entries.length === 0) return '- No standard commands detected. Add scripts/config and rerun `ackit write`.';
  return entries.map(([name, command]) => `- ${name}: \`${command}\``).join('\n');
}

function bullets(values: string[]): string {
  if (values.length === 0) return '- None detected.';
  return values.map((value) => `- \`${value}\``).join('\n');
}

function listOrNone(values: string[]): string {
  return values.length ? values.map((v) => `\`${v}\``).join(', ') : 'none detected';
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
